version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/deployment-archive

hooks:
  ApplicationStart:
    - location: scripts/run_docker_container.sh
      runas: root
      
