# version: 0.2

# env:
#   variables:
#     AWS_REGION: "ap-south-1"                   # Replace with your AWS Region
#     REPOSITORY_NAME: "flask-app"
#     IMAGE_TAG: "latest"                       # Use a simple tag like "latest"

# phases:
#   pre_build:
#     commands:
#       - echo Fetching AWS account ID...
#       - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
#       - IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:${IMAGE_TAG}"
#       - echo Logging in to Amazon ECR...
#       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
#       - echo Building the Docker image...
#   build:
#     commands:
#       - docker build -t ${IMAGE_URI} .
#   post_build:
#     commands:
#       - echo Pushing the Docker image to ECR...
#       - docker push ${IMAGE_URI}
#       - echo Build and push completed.

# artifacts:
#   files:
#     - '**/*'
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_URI/$REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $ECR_URI/$REPO_NAME:$CODEBUILD_BUILD_NUMBER $ECR_URI/$REPO_NAME:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ECR_URI/$REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_URI/$REPO_NAME:latest

artifacts:
  files:
    - '**/*'
