name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: test  # Your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}  # Ensure this secret is set in GitHub
          BUILD_TAG: ${{ github.run_number }}
        run: |
          echo "Building image: ${ECR_REPO_URL}:${BUILD_TAG}"
          docker build -t ${ECR_REPO_URL}:${BUILD_TAG} .
          docker tag ${ECR_REPO_URL}:${BUILD_TAG} ${ECR_REPO_URL}:latest

      - name: Push Docker images to ECR
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
        run: |
          docker push ${ECR_REPO_URL}:${BUILD_TAG}
          docker push ${ECR_REPO_URL}:latest

      - name: Deploy with docker-compose
        run: |
          cd /home/ec2-user/app
          docker system prune -f
          docker-compose pull
          docker-compose up -d
