name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: test  # Your self-hosted runner with ECR access

    env:
      ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}  # Full ECR URL (e.g., account-id.dkr.ecr.region.amazonaws.com/repo-name)
      BUILD_TAG: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${ECR_REPO_URL}:${BUILD_TAG} .
          docker tag ${ECR_REPO_URL}:${BUILD_TAG} ${ECR_REPO_URL}:latest

      - name: Push Docker images to ECR
        run: |
          docker push ${ECR_REPO_URL}:${BUILD_TAG}
          docker push ${ECR_REPO_URL}:latest

      - name: Deploy with docker-compose
        run: |
          cd /home/ec2-user/app
          docker system prune -f
          docker-compose pull
          docker-compose up -d
