name: Build and Deploy to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: test
    environment: dev 
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
          BUILD_TAG: ${{ github.run_number }}
        run: |
          echo "ECR_REPO_URL: ${ECR_REPO_URL}"
          echo "BUILD_TAG: ${BUILD_TAG}"
          
          # Build and tag
          docker build -t "${ECR_REPO_URL}:${BUILD_TAG}" .
          docker tag "${ECR_REPO_URL}:${BUILD_TAG}" "${ECR_REPO_URL}:latest"

      - name: Push Docker images
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
          BUILD_TAG: ${{ github.run_number }}
        run: |
          echo "Pushing: ${ECR_REPO_URL}:${BUILD_TAG}"
          docker push "${ECR_REPO_URL}:${BUILD_TAG}"
          docker push "${ECR_REPO_URL}:latest"

      - name: Deploy
        run: |
          cd /home/ec2-user/app
          docker system prune -f
          docker-compose pull
          docker-compose up -d 
