name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: test  # Aapka self-hosted runner

    env:
      AWS_REGION: us-east-1
      ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract short commit ID
        id: vars
        run: echo "COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # - name: Login to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO_URL:${{ env.COMMIT_ID }} .
          docker tag $ECR_REPO_URL:${{ env.COMMIT_ID }} $ECR_REPO_URL:latest

      - name: Push Docker images to ECR
        run: |
          docker push $ECR_REPO_URL:${{ env.COMMIT_ID }}
          docker push $ECR_REPO_URL:latest

      - name: Deploy with docker-compose
        run: |
          cd /home/ec2-user/app
          docker system prune -f
          docker-compose pull
          docker-compose up -d
