name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: test  # Aapka self-hosted runner 

    env:
      AWS_REGION: us-east-1
      ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Login to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.ECR_REPO_URL}}:${{ env.BUILD_NUMBER }} .
          docker tag $ECR_REPO_URL:${{ env.BUILD_NUMBER }} $ECR_REPO_URL:latest

      - name: Push Docker images to ECR
        run: |
          docker push $ECR_REPO_URL:${{ env.BUILD_NUMBER }}
          docker push $ECR_REPO_URL:latest

      - name: Deploy with docker-compose
        run: |
          cd /home/ec2-user/app
          docker system prune -f
          docker-compose pull
          docker-compose up -d
